/**
 * Asset Schema Types
 *
 * Defines types for asset management system data.
 * Used for ingesting and querying asset information in the knowledge base.
 */

/**
 * Criticality level for assets
 */
export type AssetCriticality = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

/**
 * Common asset categories
 * Extensible via metadata for client-specific categories
 */
export type AssetCategory =
  | 'PUMP'
  | 'VALVE'
  | 'GENERATOR'
  | 'TANK'
  | 'MOTOR'
  | 'SENSOR'
  | 'CONTROL_PANEL'
  | 'PIPE'
  | 'HVAC'
  | 'ELECTRICAL'
  | 'MECHANICAL'
  | 'INSTRUMENTATION'
  | 'OTHER';

/**
 * Asset status
 */
export type AssetStatus = 'OPERATIONAL' | 'MAINTENANCE' | 'OFFLINE' | 'DECOMMISSIONED';

/**
 * Core Asset schema
 *
 * Represents an asset from client's asset management system
 * (e.g., NCE, Maximo, SAP PM)
 *
 * @example
 * ```typescript
 * const asset: Asset = {
 *   assetId: 'P-104',
 *   name: 'Pump Station 104',
 *   description: 'Main water distribution pump for Riverside district',
 *   category: 'PUMP',
 *   location: 'Riverside Bridge',
 *   criticality: 'HIGH',
 *   status: 'OPERATIONAL',
 *   metadata: {
 *     manufacturer: 'FlowTech Industries',
 *     model: 'FT-5000',
 *     installDate: '2018-03-15',
 *     lastMaintenance: '2024-12-01',
 *     warranty: 'Active until 2026',
 *   },
 * };
 * ```
 */
export interface Asset {
  /**
   * Unique asset identifier from client system
   * Examples: "P-104", "V-201", "NCE-12345"
   */
  assetId: string;

  /**
   * Human-readable asset name
   */
  name: string;

  /**
   * Detailed description of the asset
   */
  description: string;

  /**
   * Asset category/type
   */
  category: AssetCategory | string;

  /**
   * Physical location or site
   */
  location: string;

  /**
   * Criticality level (optional)
   */
  criticality?: AssetCriticality;

  /**
   * Current operational status (optional)
   */
  status?: AssetStatus;

  /**
   * Additional metadata fields
   * Flexible structure to accommodate client-specific attributes
   *
   * Common fields:
   * - manufacturer: string
   * - model: string
   * - serialNumber: string
   * - installDate: string (ISO 8601)
   * - lastMaintenance: string (ISO 8601)
   * - nextMaintenance: string (ISO 8601)
   * - warranty: string
   * - parentAsset: string (for hierarchical assets)
   * - department: string
   * - responsible: string (owner/maintainer)
   */
  metadata?: Record<string, string>;
}

/**
 * Asset document for vector storage
 *
 * Combines asset data with embedding for semantic search
 */
export interface AssetDocument {
  /**
   * Original asset data
   */
  asset: Asset;

  /**
   * Text content for embedding
   * Typically: `${assetId} ${name} ${description} ${location}`
   */
  content: string;

  /**
   * Vector embedding (generated by OpenAI)
   */
  embedding: number[];

  /**
   * Document ID in vector store (if persisted)
   */
  documentId?: string;
}

/**
 * Safety manual or procedure document
 */
export interface SafetyDocument {
  /**
   * Unique document identifier
   */
  id: string;

  /**
   * Document title
   */
  title: string;

  /**
   * Document content/excerpt
   */
  content: string;

  /**
   * Document type
   */
  type: 'SAFETY_MANUAL' | 'PROCEDURE' | 'POLICY' | 'GUIDELINE';

  /**
   * Related asset IDs (optional)
   */
  relatedAssets?: string[];

  /**
   * Document metadata
   *
   * Common fields:
   * - version: string
   * - effectiveDate: string (ISO 8601)
   * - author: string
   * - department: string
   * - reviewDate: string (ISO 8601)
   * - category: string
   */
  metadata?: Record<string, string>;
}

/**
 * Safety document for vector storage
 */
export interface SafetyDocumentDocument {
  /**
   * Original safety document data
   */
  document: SafetyDocument;

  /**
   * Text content for embedding
   */
  content: string;

  /**
   * Vector embedding
   */
  embedding: number[];

  /**
   * Document ID in vector store (if persisted)
   */
  documentId?: string;
}

/**
 * Asset ingestion source type
 */
export type IngestionSource = 'CSV' | 'JSON' | 'PDF' | 'API' | 'SEED';

/**
 * Asset ingestion result
 */
export interface IngestionResult {
  /**
   * Number of assets/documents successfully ingested
   */
  successCount: number;

  /**
   * Number of assets/documents that failed to ingest
   */
  failureCount: number;

  /**
   * Total number of assets/documents processed
   */
  totalCount: number;

  /**
   * IDs of successfully ingested documents in vector store
   */
  documentIds: string[];

  /**
   * Errors encountered during ingestion
   */
  errors: Array<{
    /**
     * Asset ID or document identifier
     */
    itemId: string;

    /**
     * Error message
     */
    error: string;
  }>;

  /**
   * Ingestion metadata
   */
  metadata: {
    /**
     * Source type
     */
    source: IngestionSource;

    /**
     * Source file path (if applicable)
     */
    sourceFile?: string;

    /**
     * Timestamp of ingestion
     */
    timestamp: Date;

    /**
     * Duration in milliseconds
     */
    durationMs: number;
  };
}

/**
 * Asset query options for semantic search
 */
export interface AssetQueryOptions {
  /**
   * Filter by asset category
   */
  category?: AssetCategory | string;

  /**
   * Filter by location
   */
  location?: string;

  /**
   * Filter by criticality
   */
  criticality?: AssetCriticality;

  /**
   * Filter by status
   */
  status?: AssetStatus;

  /**
   * Maximum number of results
   * Default: 10
   */
  limit?: number;

  /**
   * Minimum similarity threshold (0-1)
   * Default: 0.7
   */
  minSimilarity?: number;
}

/**
 * Asset search result
 */
export interface AssetSearchResult {
  /**
   * Matched asset
   */
  asset: Asset;

  /**
   * Similarity score (0-1)
   */
  similarity: number;

  /**
   * Matched content snippet
   */
  snippet: string;

  /**
   * Document ID in vector store
   */
  documentId: string;
}

/**
 * Validates asset data
 */
export function validateAsset(asset: unknown): asset is Asset {
  if (!asset || typeof asset !== 'object') {
    return false;
  }

  const a = asset as Partial<Asset>;

  // Required fields
  if (!a.assetId || typeof a.assetId !== 'string') {
    return false;
  }
  if (!a.name || typeof a.name !== 'string') {
    return false;
  }
  if (!a.description || typeof a.description !== 'string') {
    return false;
  }
  if (!a.category || typeof a.category !== 'string') {
    return false;
  }
  if (!a.location || typeof a.location !== 'string') {
    return false;
  }

  // Optional fields type check
  if (a.criticality !== undefined && typeof a.criticality !== 'string') {
    return false;
  }
  if (a.status !== undefined && typeof a.status !== 'string') {
    return false;
  }
  if (a.metadata !== undefined && (typeof a.metadata !== 'object' || a.metadata === null)) {
    return false;
  }

  return true;
}

/**
 * Validates safety document data
 */
export function validateSafetyDocument(doc: unknown): doc is SafetyDocument {
  if (!doc || typeof doc !== 'object') {
    return false;
  }

  const d = doc as Partial<SafetyDocument>;

  // Required fields
  if (!d.id || typeof d.id !== 'string') {
    return false;
  }
  if (!d.title || typeof d.title !== 'string') {
    return false;
  }
  if (!d.content || typeof d.content !== 'string') {
    return false;
  }
  if (!d.type || typeof d.type !== 'string') {
    return false;
  }

  // Optional fields type check
  if (d.relatedAssets !== undefined && !Array.isArray(d.relatedAssets)) {
    return false;
  }
  if (d.metadata !== undefined && (typeof d.metadata !== 'object' || d.metadata === null)) {
    return false;
  }

  return true;
}

/**
 * Creates searchable content from asset for embedding
 */
export function assetToContent(asset: Asset): string {
  const parts = [
    `Asset ID: ${asset.assetId}`,
    `Name: ${asset.name}`,
    `Description: ${asset.description}`,
    `Category: ${asset.category}`,
    `Location: ${asset.location}`,
  ];

  if (asset.criticality) {
    parts.push(`Criticality: ${asset.criticality}`);
  }

  if (asset.status) {
    parts.push(`Status: ${asset.status}`);
  }

  if (asset.metadata) {
    Object.entries(asset.metadata).forEach(([key, value]) => {
      parts.push(`${key}: ${value}`);
    });
  }

  return parts.join('\n');
}

/**
 * Creates searchable content from safety document for embedding
 */
export function safetyDocumentToContent(doc: SafetyDocument): string {
  const parts = [
    `Document ID: ${doc.id}`,
    `Title: ${doc.title}`,
    `Type: ${doc.type}`,
    `Content: ${doc.content}`,
  ];

  if (doc.relatedAssets && doc.relatedAssets.length > 0) {
    parts.push(`Related Assets: ${doc.relatedAssets.join(', ')}`);
  }

  if (doc.metadata) {
    Object.entries(doc.metadata).forEach(([key, value]) => {
      parts.push(`${key}: ${value}`);
    });
  }

  return parts.join('\n');
}

/**
 * Normalizes asset category to standard enum value
 */
export function normalizeAssetCategory(category: string): AssetCategory | string {
  const normalized = category.toUpperCase().replace(/[^A-Z]/g, '_');

  const standardCategories: AssetCategory[] = [
    'PUMP',
    'VALVE',
    'GENERATOR',
    'TANK',
    'MOTOR',
    'SENSOR',
    'CONTROL_PANEL',
    'PIPE',
    'HVAC',
    'ELECTRICAL',
    'MECHANICAL',
    'INSTRUMENTATION',
    'OTHER',
  ];

  // Check if normalized matches any standard category
  if (standardCategories.includes(normalized as AssetCategory)) {
    return normalized as AssetCategory;
  }

  // Return original if no match
  return category;
}
